import type { Metadata } from "next";
import "./globals.css";
import { spaceGrotesk } from "@/app/lib/fonts";
import Header from "@/app/ui/header";

export const metadata: Metadata = {
  title: "Hgareli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased md:px-[10vh] px-[2vh]`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
